### ISSUE TITLE
Need mappings file

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-greek#16]
The original GNT mappings file was removed due to copyright concerns.  We need a mapping file that removes these restrictions and adds MARBLE ids.  The mapping file should show the correspondences between:

- NA27
- NA28
- MARBLE IDs
- Nestle1904
- Other GNT editions we support in the future

It should be in XML or JSON or TSV - we can discuss which is best for this purpose (no bikeshedding allowed!)

We can't publish the text of NA27 or NA28, but we can identify equivalent positions in our mapping.

**Comment by jonathanrobie** [comment]
In theory, the MARBLE mapping should match the NA27 column word for word.  Perhaps the best thing to do is to assume this accurate and see where it is not?

**Comment by pdurusau** [comment]
I don't know about the MARBLE mapping but the 1904 Nestle text is reported to differ from the present NA in 700 passages. The Text of the New Testament by Aland and Aland, 2nd ed., 1989, page 20. I didn't see a table of those differences.

**Comment by RobH123** [comment]
Are you guys considering mapping to the SR (Statistical Restoration) GNT? It's currently in beta at https://greekcntr.org/collation/index.htm. Once released, it's promised to have a free and open license.

**Comment by klosoter** [comment]
I think a TSV sorted by **verse** ids works best for the mapping file. This would give a clear readable overview of the GNT versions.

Assuming that we can't publish the NA27 and NA28 text (what about MARBLE, though?), I believe this would result in the following column headers:

| NA1904_ID | NA1904_Text | NA27_ID | NA28_ID | SBLGNT_ID | SBLGNT_Text | MARBLE_ID | MARBLE_Text |
| ------------ | -- | -- | -- | -- | -- | -- | -- |
| 40001001001 | Βίβλος | 40001001001 | 40001001001 | 40001001001 | Βίβλος | 04000100100002 | Βίβλος |

**Comment by klosoter** [comment]
Also, I've found 335 entries in the original mappings file that can be merged with other, fuller entries:

I've left out the text of most GNT versions, but see this example, where you can see that some entries exist wholly inside more complete entries:
![image](https://user-images.githubusercontent.com/61023061/172822257-0d0724c2-e7f9-4e17-965f-d4af6b7f21c4.png)

See here for all duplicates:
[duplicate_entries.xlsx](https://github.com/Clear-Bible/macula-greek/files/8869310/duplicate_entries.xlsx)

**Comment by jonathanrobie** [comment]
> I think a TSV sorted by verse (and then word) ids works best for the mapping file. This would give a clear readable overview of the GNT versions.

Yes, and it's a good match for people who use spreadsheets.

**Comment by jonathanrobie** [comment]
> I've left out the text of most GNT versions

You can safely use the text of the SBLGNT.
