### ISSUE TITLE
Extracting domains and senses from MARBLE

### ISSUE THREAD

**Issue by klosoter** [Clear-Bible/macula-greek#21]
We plan to construct the data we use from MARBLE in the following way:

1. We collect `//LEXMeaning`s from the lexicon files and group them by `LEXReference`, the 'marbleId' so to speak.
2. We also collect English Glosses from `//LEXSense[@LanguageCode="en"]//Gloss` and Domains from `//LEXDomain` and the EntryCode from `@EntryCode`. (and possibly the SubDomain from `//LEXSubDomain`
3. We then look up the (sub)domain identifiers in `SDBG-DOMAINS1.XML`

Assuming this is all connected, we create the following attributes to our tree words:

- `domain="DomainNumber:DomainName"`
- `sdbg="Lemma:EntryCode:Glosses"`

When there are multiple entries/senses/domains for one word/ref, we concatenate them with "|"

**Comment by klosoter** [comment]
Do we need the SubDomain too? If so, how would we add that to the domain attribute?

`domain="DomainNumber:DomainName:SubDomainName"` ?

**Comment by ryderwishart** [comment]
> We need the SubDomain too. How would we add that to the domain attribute?
> 
> `domain="DomainNumber:DomainName:SubDomainName"` or `domain="SubDomainNumber:DomainName:SubDomainName"` since the subdomain number includes the domain number?

I like the idea of putting the number first.

**Comment by klosoter** [comment]
In both cases, the number is first. I'm thinking about which number to use. Example:
Domain: "Physical Impact"
DomainNumber: 019
SubDomain: "Press"
SubDomainNumber: 019005

So, I guess it makes sense to use only the SubDomainNumber since it contains (expands) the DomainNumber. And then, number first:

``` html
<w domain="019005:Physical Impact:Press" sdbg"..."/>
```

**Comment by klosoter** [comment]
But is there a more preferable way to add both domain names?

**Comment by ryderwishart** [comment]
Ah, that makes more sense. I would think it would be best to simply use the subdomain number alone. Unless we want to have everything there, then I would think you could do `domain#:subdomain#`, or just do `domain="domain#:domainlabel" subdomain="subdomain#:subdomainlabel"`.

**Comment by jonathanrobie** [comment]
On second thought ... how about:

```
domain="subdomainID:domainLabel:subdomainLabel"
```

```
domain="001014:Population Centers"
```

**Comment by ryderwishart** [comment]
@klosoter, want me to do this or do you want to take care of it?

**Comment by klosoter** [comment]
If you have the time, please!

**Comment by klosoter** [comment]
It seems that some domain and ln data got lost:

Multiple entries got joined into one:

```xml
domain="010002033003" ln="10.24"
```
should be
```xml
domain="010002 033003" ln="10.24 33.19"
```

And domains with only 3-digits have gotten the value "" (possibly because it is redundant since `ln` also has these digits).

**Comment by klosoter** [comment]
See the new data file [here](https://github.com/Clear-Bible/macula-greek/blob/main/sources/MARBLE/SDBG/MARBLE-macula-domains-ln.xml) to see how the MARBLE data we use is connected to our nodes.

**Comment by klosoter** [comment]
See new pull request
