### ISSUE TITLE
AA2 in @frame

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-greek#30]
Greek frame attributes have `AA2` values, which are not valid in propbank, e.g.

```xml
19-hebrews.xml:                     frame="AA2:n58009027006 A0:n58009027008">ἀπόκειται</w>
```

We also have `A2` values:

```xml
27-revelation.xml:               frame="A0:n66022018002 A2:n66022018005">Μαρτυρῶ</w>
```

These AA2 values were present in the source that we created this repo from.  Some possibilities:

- They may well have been intended as A2 values
- They could be AA values, but this seems unlikely for Greek

Can we safely assume they are A2 values and change them to A2?

**Comment by rkjtan** [comment]
For reference on Semantic Roles/Verb Frames, please see
[2013 From Syntactic TreeBank to Predicate Argument Information.pptx](https://github.com/Clear-Bible/macula-greek/files/9294741/2013.From.Syntactic.TreeBank.to.Predicate.Argument.Information.pptx)

**Comment by jonathanrobie** [comment]
> For reference on Semantic Roles/Verb Frames, please see
> [2013 From Syntactic TreeBank to Predicate Argument Information.pptx](https://github.com/Clear-Bible/macula-greek/files/9294741/2013.From.Syntactic.TreeBank.to.Predicate.Argument.Information.pptx)

For Greek, I have these prefixes:

- A
- A0
- A1
- A2
- AA2

For Hebrew, I have these prefixes:

- A0
- A1
- A2
- AA

**Comment by jonathanrobie** [comment]
I need a clear description of the semantics of each of those prefixes.
