### ISSUE TITLE
Word senses

### ISSUE THREAD

**Issue by jonathanrobie** [Clear-Bible/macula-greek#33]
We need to put word sense data into the repository. It should not be woven into the trees, it should be available as a separate dataset.

**Comment by jonathanrobie** [comment]
Note that MARBLE data gives another take on word senses, and we have already integrated that data into the trees.

**Comment by jonathanrobie** [comment]
Here it is in XML with a schema

[Senses.zip](https://github.com/Clear-Bible/macula-greek/files/8970785/Senses.zip)

**Comment by rkjtan** [comment]
For reference, please see
[2021 Building on the Shoulder of Giants (prepublication draft).pdf](https://github.com/Clear-Bible/macula-greek/files/9294358/2021.Building.on.the.Shoulder.of.Giants.prepublication.draft.pdf)

**Comment by jonathanrobie** [comment]
@rkjtan 

Can you please clarify the identifier format used for instances?

<Senses>
<StrongNumber>0001</StrongNumber>
<Lemma>אָב</Lemma>
<SenseNumber>3</SenseNumber>
<English>of ancestors (modifier in construct relation)</English>
<Chinese>家族</Chinese>
<Instances>040360080400030 040250150380020

**Comment by rkjtan** [comment]
Strong Number 0001 is shown as having potentially up to 3 senses. When there is only one sense, you just see sense 1 for a Strong Number. The instances just have the morphIds of the word occurrences. The most frequently used English gloss is shown to help with human evaluation.
![image](https://user-images.githubusercontent.com/5300526/184022426-941e468e-6958-4424-9f1b-50f4ad6cca9a.png)
There's also a Category column (off screen in screenshot) that indicates part of speech: 1 is noun, 2 is verb, 3 is adjective.

**Comment by jonathanrobie** [comment]
The instances don't seem to be in morphId format.

040360080400030 
BBCCCVVVWWW...0030?

**Comment by rkjtan** [comment]
Thanks for pointing out my mistake here. It is actually the nodeId: A 15-digit unique id in the format BBCCCVVVWWWSSSL
where 
BB => zero-padded book
CCC => zero-padded chapter
VVV => zero-padded verse
WWW represents the beginning position (the Nth word) of a node/sub-tree
SSS represents the SPAN of a node (how many words it covers)
L (Level) is used to distinguish nodes which have the same span (in cases of non-branching nodes)

**Comment by jonathanrobie** [comment]
Thanks.  These nodeIds won't match what's in the public repo, but they do match ids in this repo:

github/Clear/trees-oshb/sources/trees-groves-full/

For instance, from the previous example:

//@*[.="040360080400030"]/parent::*

Returns this:

```xml
<Node Id="3.48" Cat="noun" Start="14" End="14" Lemma=")FB" Accusative="False" Dative="False" Vocative="False" Nominative="False" GreekStrong="3962" SenseNumber="3" StrongNumber="1" Length="3" UnicodeLemma="אָב" Gender="Masculine" KetivQere="" Person="Third" UnicodeNoAccent="אָבִי" English="father of" Label="" Number="Singular" Greek="patro\s" Analysis="ncmsc" MichiganCode=")FBI73Y" kqAlternate="" NounType="Common" Notes="" morphId="040360080111" StrongNumberX="0001" State="Construct" EncodeAccent=")FBI73Y" Language="H" Chinese="~父家" morphIdC="04036008040003" Unicode="אָבִ֖י" Ref="{}" RB="{1}" NB="{}" AR="{}" BR="{}" nodeId="040360080400030">אָבִ֖י</Node>
```

But here's something confusing - compare the nodeId to the morphId, they don't seem to have the same BBCCCVVVWWW:

040360080111
040360080400030

So creating a mapping to morphId using that file is probably the easiest way to do this.  I'll comment on that next ...

**Comment by jonathanrobie** [comment]
This query gives me the mapping to morphId from github/Clear/trees-oshb/sources/trees-groves-full/:

```xquery

for $node in //Node[empty(Node)]
let $sense := $node/@SenseNumber
let $strong := $node/@StrongNumber
let $lemma := $node/@UnicodeLemma
let $text := $node/text()
let $mandarin := $node/@Chinese
let $english := $node/@English
let $morphId := $node/@morphId
order by $morphId
return
    <w>
      {
        $morphId,
        $strong,
        $lemma,
        $sense,
        $mandarin,
        $english,
        string($text)
      }
    </w>  
```

Sample output:

```xml
  <w morphId="010010010011" StrongNumber="9996" UnicodeLemma="בְּ" SenseNumber="0" Chinese="" English="in">בְּ</w>
  <w morphId="010010010012" StrongNumber="7225" UnicodeLemma="רֵאשִׁית" SenseNumber="1" Chinese="起初" English="beginning">רֵאשִׁ֖ית</w>
  <w morphId="010010010021" StrongNumber="1254" UnicodeLemma="ברא_1" SenseNumber="1" Chinese="创造" English="he created">בָּרָ֣א</w>
  <w morphId="010010010031" StrongNumber="430" UnicodeLemma="אֱלֹהִים" SenseNumber="1" Chinese="神" English="God">אֱלֹהִ֑ים</w>
  <w morphId="010010010041" StrongNumber="853" UnicodeLemma="אֵת_1" SenseNumber="0" Chinese="-" English="-">אֵ֥ת</w>
  <w morphId="010010010051" StrongNumber="9998" UnicodeLemma="הַ" SenseNumber="0" Chinese="" English="the">הַ</w>
  <w morphId="010010010052" StrongNumber="8064" UnicodeLemma="שָׁמַיִם" SenseNumber="1" Chinese="诸天" English="heavens">שָּׁמַ֖יִם</w>
  <w morphId="010010010061" StrongNumber="9999" UnicodeLemma="וְ" SenseNumber="0" Chinese="与" English="and">וְ</w>
  <w morphId="010010010062" StrongNumber="853" UnicodeLemma="אֵת_1" SenseNumber="0" Chinese="-" English="-">אֵ֥ת</w>
  <w morphId="010010010071" StrongNumber="9998" UnicodeLemma="הַ" SenseNumber="0" Chinese="" English="the">הָ</w>
  <w morphId="010010010072" StrongNumber="776" UnicodeLemma="אֶרֶץ" SenseNumber="2" Chinese="地" English="earth">אָֽרֶץ׃</w>
  <w morphId="010010020011" StrongNumber="9999" UnicodeLemma="וְ" SenseNumber="0" Chinese="且" English="now">וְ</w>
  <w morphId="010010020012" StrongNumber="9998" UnicodeLemma="הַ" SenseNumber="0" Chinese="" English="the">הָ</w>
  <w morphId="010010020013" StrongNumber="776" UnicodeLemma="אֶרֶץ" SenseNumber="2" Chinese="地" English="earth">אָ֗רֶץ</w>
  <w morphId="010010020021" StrongNumber="1961" UnicodeLemma="היה" SenseNumber="0" Chinese="是" English="she was">הָיְתָ֥ה</w>
  <w morphId="010010020031" StrongNumber="8414" UnicodeLemma="תֹּהוּ" SenseNumber="1" Chinese="混沌" English="formless">תֹ֙הוּ֙</w>
  <w morphId="010010020041" StrongNumber="9999" UnicodeLemma="וְ" SenseNumber="0" Chinese="又" English="and">וָ</w>
  <w morphId="010010020042" StrongNumber="922" UnicodeLemma="בֹּהוּ" SenseNumber="1" Chinese="空虚" English="empty">בֹ֔הוּ</w>
  <w morphId="010010020051" StrongNumber="9999" UnicodeLemma="וְ" SenseNumber="0" Chinese="且" English="">וְ</w>
  <w morphId="010010020052" StrongNumber="2822" UnicodeLemma="חֹשֶׁךְ" SenseNumber="1" Chinese="黑暗" English="darkness">חֹ֖שֶׁךְ</w>
  <w morphId="010010020061" StrongNumber="5921" UnicodeLemma="עַל_2" SenseNumber="0" Chinese="在" English="over">עַל־</w>
  <w morphId="010010020071" StrongNumber="6440" UnicodeLemma="פָּנֶה" SenseNumber="2" Chinese="面上" English="surface of">פְּנֵ֣י</w>
  <w morphId="010010020081" StrongNumber="8415" UnicodeLemma="תְּהוֹם" SenseNumber="1" Chinese="深渊" English="deep">תְה֑וֹם</w>
```

**Comment by jonathanrobie** [comment]
Here's the output from that last query.  It should be easier for Seth to map from.

[senses-ot.zip](https://github.com/Clear-Bible/macula-greek/files/9308240/senses-ot.zip)

**Comment by rkjtan** [comment]
On the nodeIds, I shouldn't have just given you the format for the Greek. For the Hebrew, WWW  actually counts the Hebrew consonants rather than the Hebrew words. (So, if you ignore the last 3 digits for span, the value matches the morphIdC.)

**Comment by jonathanrobie** [comment]
Sense number IS the data we use here.   It is not as good for Greek as it is for Hebrew because of the relative size of the corpus. @rkjtan - I think we agreed to add it for Greek anyway?  Your call.

**Comment by rkjtan** [comment]
Yes, we add it anyway. In some form we'll need to make clear to users that both the Hebrew & Greek Word Senses are calculated based on probabilities (& the Greek guesses are less good due to smaller size of the corpus) & are suggestive & generally helpful, but nothing like an authoritative lexicon they're used to.
