### ISSUE TITLE
Invalid xml:ids on <wg> elements in lowfat

### ISSUE THREAD

**Issue by pdurusau** [Clear-Bible/macula-greek#35]
Invalid xml:ids are appearing on <wg> elements in lowfat. 

For example:
MAT 1:1
<wg role="p" xml:id="400010010010081" class="np" rule="NPofNP">
or
 <wg class="np" rule="NPofNP" xml:id="400010010020070">

Words within those <wg> appear to have valid xml:ids.

The issue being xml:ids can only start with a name start character, which excludes all digits. 

Acts 1:1
<wg class="cl" rule="ClCl2" xml:id="440010010080540">
            <wg class="cl" rule="Np2CL" cltype="Minor" xml:id="440010010080021">
               <wg class="np" rule="intjNP" xml:id="440010010080020">

Checking with BaseX, there are 98,248 invalid xml:ids in the lowfat database. For some reason the n that prepends the xml:ids on words isn't being used on wg.

**Comment by jonathanrobie** [comment]
Fixed a long time ago.  Closing now.
