### ISSUE TITLE
Add USFM book-, verse-, and word-level identifiers

### ISSUE THREAD

**Issue by ryderwishart** [Clear-Bible/macula-greek#4]
Word-level identifiers should use `!` syntax for now, pending any updates on [this issue](https://github.com/usfm-bible/tcdocs/issues/18).

- [x] Convert `@osisId` to `@ref` in the TEI trees 
- [x] Convert `@osisId` to `@ref` in the GNT lowfat trees

**Comment by ryderwishart** [comment]
@jonathanrobie The Macula Greek Node trees have sentence IDs that indicate ranges like this: `<Sentence ID="Jud1:1:1-1:1:17">`

Is it fine with you if I change this to `<Sentence startRef="JUD 1:1!1" endRef="JUD 1:1!17">` to be USFM compliant?

**Comment by ryderwishart** [comment]
Another option would be to call them `ref` and `endRef`. Doesn't make any difference to me.

**Comment by jonathanrobie** [comment]
USFM references allow ranges.   Here's an example from https://ubsicap.github.io/usfm/notes_basic/xrefs.html?highlight=references:

> Lk 3.1-18
