### ISSUE TITLE
Looking up a sentence by reference in the SBLGNT `node` tree

### ISSUE THREAD

**Issue by gwd** [Clear-Bible/macula-greek#86]
Hello!  As always thank you for making this work available; it's a massive enabler for people like me trying to create Biblical resources.

I just spent most of the day working on parsing the data in the [biblicalhumanities SBLGNT repo](https://github.com/biblicalhumanities/greek-new-testament/tree/master/syntax-trees/sblgnt).  It looks like the [SBLGNT nodes directory](https://github.com/Clear-Bible/macula-greek/tree/main/SBLGNT/nodes) is meant to be approximately the same.  Unfortunately, it looks like the `node` lost the verse references?  Looking at [Jude](https://github.com/Clear-Bible/macula-greek/blob/main/SBLGNT/nodes/26-jude.xml) I don't see how one would find the sentence that contains a particular verse (unlike [Jude in this repo](https://github.com/biblicalhumanities/greek-new-testament/blob/master/syntax-trees/sblgnt/xml/26-jude.xml), which contains a parseable range in the `Sentence.ID` field).

Obviously I could go with the `lowfat` option, but I'm not sure that would suit.  Is there a recommended way to look up the sentence in the new schema?  Or could we add the sentence ID back in?

Thanks in adavance!

**Comment by jonathanrobie** [comment]
I just looked at the current `Node` representation for both Nestle1904 and SBLGNT, both do have sentences, SBLGNT does not have the sentence references.

Here it is in Nestle1904:

https://raw.githubusercontent.com/Clear-Bible/macula-greek/main/Nestle1904/nodes/01-matthew.xml

```xml
<Sentences>
  <Sentence ref="MAT 1:1!1-1:1!8">
    <Trees>
      <Tree>
        <Node Cat="S" Head="0" nodeId="400010010010083">
          <Node Cat="CL" Start="0" End="7" Rule="P2CL" Head="0" ClType="Verbless" nodeId="400010010010082">
            <Node Cat="P" Start="0" End="7" Rule="Np2P" Head="0" nodeId="400010010010081">
              <Node Cat="np" Start="0" End="7" Rule="NPofNP" Head="0" nodeId="400010010010080">
                <Node Cat="np" Start="0" End="0" Rule="N2NP" Head="0" nodeId="400010010010011">
                  <Node xml:id="n40001001001" ref="MAT 1:1!1" Cat="noun" Start="0" End="0" StrongNumber="976" UnicodeLemma="βίβλος" Gender="Feminine" Number="Singular" FunctionalTag="N-NSF" Type="Common" morphId="40001001001" NormalizedForm="Βίβλος" Case="Nominative" Unicode="Βίβλος" FormalTag="N-NSF" nodeId="400010010010010" Gloss="[The] book" LexDomain="033005" LN="33.38">Βίβλος</Node>
                </Node>```

Here it is in SBLGNT - without the reference attributes at the Sentence level:

https://raw.githubusercontent.com/Clear-Bible/macula-greek/main/SBLGNT/nodes/01-matthew.xml

```xml
<Sentences>
<Sentence>
<Trees>
<Tree>
<Node Cat="S" Head="0" nodeId="400010010010083" Length="8">
  <Node Id="2.1" Cat="CL" Start="0" End="7" Rule="P2CL" Head="0" ClType="Verbless" nodeId="400010010010082" Length="8">
    <Node Id="2.2" Cat="P" Start="0" End="7" Rule="Np2P" Head="0" nodeId="400010010010081" Length="8">
      <Node Id="2.3" Cat="np" Start="0" End="7" Rule="NPofNP" Head="0" nodeId="400010010010080" Length="8">
        <Node Id="2.4" Cat="np" Start="0" End="0" Rule="N2NP" Head="0" nodeId="400010010010011" Length="1">
          <Node Id="2.5" Cat="noun" Start="0" End="0" StrongNumber="976" UnicodeLemma="βίβλος" Unicode="Βίβλος" English="book" Number="Singular" Type="Common" morphId="40001001001" Mandarin="谱" Language="G" Case="Nominative" Gender="Feminine" nodeId="400010010010010" xml:id="n40001001001" ref="MAT 1:1!1" NormalizedForm="βίβλος" FunctionalTag="N-NSF" FormalTag="N-NSF" Gloss="[The] book" LexDomain="033005" LN="33.38" status="mapped">Βίβλος</Node>
        </Node>
```

So it looks like:

1. It's a bug in SBLGNT
2. Even in SBLGNT, the sentences are actually there, so you can search for, e.g. sentences that contain words from particular verses.  The TSV may help with that

Does that help?

**Comment by gwd** [comment]
Hey Jonathan,

FYI my use case is as follows: I'm using GPT to write some [commentary for language learners](https://gitlab.com/laleo-language/sblgnt-commentary).  I'm experimenting with feeding a "compressed" from of the syntax trees into it to help increase the accuracy; so I need a function which accepts a verse reference and returns all sentences which contain or are contained by that verse.

For the time being I'm just using the old trees from the other repo, as I doubt there have been massive changes.  From my perspective, ideally this project would add back in the sentence IDs, and then I could just switch to the latest data; but if at some point I need the newer information, it's good to know that I could fish it out of the morphid tag if I need to.

Thanks!

**Comment by jonathanrobie** [comment]
Cool!  FWIW, I have used Lowfat for this, because the Treedown display was designed for language learners.

**Comment by gwd** [comment]
Is the content different somehow?  I thought it was mainly that the lowfat had less "extraneous" information ("fat").

**Comment by RickBrannan** [comment]
@gwd ,  RE: adding a `ref` attribute to the `Sentence` element in SBLGNT nodes, I'm working on that and will hopefully get changes up to main next week.

**Comment by jacobwegner** [comment]
@gwd: I forgot to circle back to this issue, but we landed #87 in the [24.02.10 release](https://github.com/Clear-Bible/macula-greek/releases/tag/24.02.10).

Please let us know if that `ref` change will work, and if so, I think we can consider this issue resolved!

**Comment by gwd** [comment]
Hey all!  Just got a chance to port my golang XML parsing code to use the new format; seems to work as expected.   I'll give the content a more thorough test later, but if I have any further issues I'll raise a new ticket.  Thanks!

**Comment by gwd** [comment]
x
